m=[]
a1=input("Enter the name of 1st movie :")
a2=input("Enter the name of 2nd movie :")
a3=input("Enter the name of 3rd movie :")
a4=input("Enter the name of 4th movie :")
a5=input("Enter the name of 5th movie :")
m.append(a1)
m.append(a2)
m.append(a3)
m.append(a4)
m.append(a5)
print("The 1st and last movies are :",m[0],"and",m[-1],"respectively")
m.sort()
print("The movies are sorted :",m)
m.sort(reverse=True)
print("The reverse of sorted list :",m)
print("The movie we removed :",m.pop(2))
remov=input("Enter the movie name to remove :")
if remov in m:
    m.remove(remov)
    print("Movie removed")
else:
    print("Movie not found")
m.insert(1,"Interteller")
print("Updated list :",m)
tup= tuple(m,)
print("The tuple :",tup)
b=input("Enter movie name :")
print("Its index is :",tup.index(b))
print("The time it appears :",tup.count(b))
print("Number of movies :",len(m))
z=input("Enter new movie :")
#tup.append(z)
print("Tuples are immutable")
